### PR TITLE
Mouse 1.3

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
### Main improvements in this PR:
- Fixes ([PR 382](https://github.com/SysBioChalmers/Human-GEM/pull/382)):
  - resolves issues reported in #11, #12, #13
- Fixes (commit 88826a8e5b67669e1c2888500e885035a782b04b):
  - change compartment abbreviation from `p` to `x`, to sync with changes made in Human-GEM [PR 341](https://github.com/SysBioChalmers/Human-GEM/pull/341)
- Features (commit f74fd2beece82ddc4137e342b6749156bebccd23):
  - update ortholog pairs from Alliance of Genomes to ver `5.1.0`
- Style (PR #9):
  - add `.gitattributes` to ensure consistent LF (\n) line endings
  - add citation
  - rename branches: `master` --> `main`, `devel` --> `develop`

### CODE REVIEW

**Review by johan-gson — APPROVED** [review]

**Review by mihai-sysbio — APPROVED** [review]
Looks good to me! Just a heads up, it would be nice to mention in the Readme or the release text what version of Human-GEM this is based. Also, there is an update of orthologs, perhaps the reason behind that should also be stated.

**Comment by haowang-bioinfo** [comment]
> would be nice to mention in the Readme or the release text what version of Human-GEM this is based. Also, there is an update of orthologs, perhaps the reason behind that should also be stated.

Good point, will include this info to the release message

**Comment by JonathanRob** [comment]
Very nice, @haowang-bioinfo!

I don't think I've ever seen this before though:
image

**Review by JonathanRob — APPROVED** [review]

**Comment by JonathanRob** [comment]
I think it's ok - it almost seems like a bug; only 8 files changed. The 8... fell over... or something.

**Comment by haowang-bioinfo** [comment]
> I think it's ok - it almost seems like a bug

Instead of updating the huge raw data of ortholog pairs, a more decent way might be just logging the extracted pairs in `tsv` format

To release new `Mouse-GEM` with all the changes, a new `Human-GEM` release probably should also be pushed?

**Comment by mihai-sysbio** [comment]
> Instead of updating the huge raw data of ortholog pairs, a more decent way might be just logging the extracted pairs in `tsv` format

Very good idea!

> To release new `Mouse-GEM` with all the changes, a new `Human-GEM` release probably should also be pushed?

Another option is to link either the Human-GEM PR that was used, or the merge commit hash https://github.com/SysBioChalmers/Human-GEM/commit/ff109f2283e06bc741ccd991c87ecc11a87a17a6 .

**Comment by haowang-bioinfo** [comment]
> merge commit hash https://github.com/SysBioChalmers/Human-GEM/commit/ff109f2283e06bc741ccd991c87ecc11a87a17a6 .

this is an easier option

**Pull request merged**
